apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xee840rsd-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xee840rsd-dotnet-basic-gitops